[build-system]
# Should be mirrored in requirements-build.txt
requires = [
    "ninja",
    "packaging",
    "setuptools == 69.5.1",
    # "setuptools >= 49.4.0",
    # "torch == 2.1.2",
    "torch == 2.4.0", # H20 GPU
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    # "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    # "I",
]
ignore = [
    # star imports
    "F405", "F403",
    # lambda expression assignment
    "E731",
    # line too long, handled by black formatting
    "E501",
]
